// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt sql.NullTime
}

type Entry struct {
	ID        int64
	AccountID int64
	// can be negative or positive
	Amount    int64
	CreatedAt sql.NullTime
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	//  it can only be positive
	Amount    int64
	CreatedAt sql.NullTime
}
